In [2]:
import numpy as np
a=np.array([1,2,3]) #vector
print(a)
print(type(a))



[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a.dtype

dtype('int32')

In [4]:
import numpy as np
a=np.array([1,2,3],dtype=float) 
print(a)
print(type(a))



[1. 2. 3.]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
a=np.array([1,2,3],dtype=bool) 
print(a)
print(type(a))



[ True  True  True]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a=np.array([1,2,3],dtype=complex) 
print(a)
print(type(a))



[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
a=np.array(([1,2,3],[4,5,6])) 
print(a)
print(type(a))



[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [15]:
print(np.arange(4))
print(np.arange(4.0))
print(np.arange(3,8))
print(np.arange(3,8,dtype=float))
print(np.arange(3,8,2))
print(np.arange(3,8,-1))
print(np.arange(8,3,-1))

[0 1 2 3]
[0. 1. 2. 3.]
[3 4 5 6 7]
[3. 4. 5. 6. 7.]
[3 5 7]
[]
[8 7 6 5 4]


In [16]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [19]:
print(np.arange(6).reshape(3,2))
a=np.arange(9)
print("________________")
print(np.reshape(a,(3,3)))

[[0 1]
 [2 3]
 [4 5]]
________________
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [27]:
print(np.linspace(2.0,3.0,num=5))
print(np.linspace(2.0,3.0,num=5,endpoint=False))
print(np.linspace(2.0,3.0,num=5,retstep=True))
print(np.identity(4))

[2.   2.25 2.5  2.75 3.  ]
[2.  2.2 2.4 2.6 2.8]
(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)
print("******************")
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.itemsize)
print("*******************")
print(a2.ndim)
print(a2.shape)
print(a2.size)
print(a2.itemsize)
print("********************")
print(a3.ndim)
print(a3.shape)
print(a3.size)
print(a3.itemsize)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
******************
1
(10,)
10
4
*******************
2
(3, 4)
12
8
********************
3
(2, 2, 2)
8
4


In [40]:
#scaler oprations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print()
print(a2)
print("******************")
print(a1+a2) #vector
print()
print(a1-a2)
print()
print(a1*a2)#element wise
print()
print(a1/2) #scaler
print()
print(a1**2)#scaler
print()
print(a1//2)#scaler

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
******************
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]

[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]]


In [41]:
#sort operator
a=np.array([1,34,645,12,65,23,87])
np.sort(a)

array([  1,  12,  23,  34,  65,  87, 645])

In [46]:
b=np.random.randint(1,100,24).reshape(6,4)
print(np.sort(b,axis=0))
print("************************")
print(np.sort(b,axis=1))

[[ 9  7 15 20]
 [18  7 32 26]
 [21 36 53 35]
 [75 43 71 43]
 [82 80 71 75]
 [86 94 99 83]]
************************
[[15 26 75 80]
 [ 7 18 75 99]
 [ 9 32 43 43]
 [20 71 86 94]
 [21 35 36 53]
 [ 7 71 82 83]]


In [52]:
#np.concatinate: this function concatinate a sequence of arange along and existing axis
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1)
print()
print(a2)
print("**************************")
print(np.concatenate((a1,a2),axis=0))
print()
print(np.concatenate((a1,a2),axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
**************************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [55]:
#np.where:return the index
a=np.array([58,59,15,43,66,88])
print(np.where(a>49))
print(np.where(a>50,0,a))

(array([0, 1, 4, 5], dtype=int64),)
[ 0  0 15 43  0  0]


In [58]:
arr=np.array([1,2,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)
print()
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
arr2=np.array_split(arr1,3)
print(arr2)

[array([1, 2]), array([4, 5]), array([6])]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [3]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(np.array_split(arr1,3))
print()
print(np.array_split(arr1,3,axis=1))
print()
print(np.array_split(arr1,3,axis=0))


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [9]:
#sort():
a=np.array([4,5,1,3,6,7])
print(np.sort(a))
print(np.sort(a)[::-1])
print(a)
a.sort()
print(a)

[1 3 4 5 6 7]
[7 6 5 4 3 1]
[4 5 1 3 6 7]
[1 3 4 5 6 7]


In [12]:
b=np.random.randint(1,100,24).reshape(6,4)
print(b)
print()
print(np.sort(b,axis=0))
print()
print(np.sort(b,axis=1))

[[88 94 82 60]
 [87 97 19 34]
 [62 68 97 12]
 [55 44 96 17]
 [16 19 51 17]
 [97 61 25  1]]

[[16 19 19  1]
 [55 44 25 12]
 [62 61 51 17]
 [87 68 82 17]
 [88 94 96 34]
 [97 97 97 60]]

[[60 82 88 94]
 [19 34 87 97]
 [12 62 68 97]
 [17 44 55 96]
 [16 17 19 51]
 [ 1 25 61 97]]


In [15]:
#iteration
x=np.array([1,2,3,4,5])
for i in x:
    print(i)
print()

y=np.array([[1,2],[3,4]])
for j in y:
    print(j)
print()
# for 2D array
for i in  np.nditer(y):
    print(i)

1
2
3
4
5

[1 2]
[3 4]

1
2
3
4


In [16]:
#polymorphism
#(method overloading)
class pyprog:
    def __init__(self,name):
        self.name=name
    def show(self):
        print("create of python:",self.name)
class javapro:
    def __init__(self,name):
        self.name=name
    def show(self):
        print("creater of java is:",self.name)
        
p1=pyprog("rajan")
p1.show()
p2=javapro("harsh")
p2.show()

create of python: rajan
creater of java is: harsh


In [17]:
#inheritace:(single level inheritance)
class person:
    def __init__(self,name):
        self.name=name
    def show(self):
        print("create of python:",self.name)
class professor(person):
    pass
p1=professor("rajan")
p1.show()

create of python: rajan


In [18]:
#inheritace:(hyrarki inheritance)
class person:
    def __init__(self,name):
        self.name=name
    def show(self):
        print("create of python:",self.name)
class professor(person):
    pass
class teacher(professor):
    pass
p1=teacher("rajan")
p1.show()

create of python: rajan


In [19]:
#inheritace:(multiple  inheritance)
class person:
    def __init__(self,name):
        self.name=name
    def show(self):
        print("create of python:",self.name)
class professor:
    def credit(Self):
        print("he teacher python")
class teacher(person,professor):
    pass
    
p1=teacher("rajan")
p1.show()
p1.credit()

create of python: rajan
he teacher python


In [2]:
#super()
class Myclass:
    def fun(self):
        print("from parent")
class child(Myclass):
    def fun(self):
        print("from child")
        super().fun()
        print("back to child")
a1=child()
a1.fun()

from child
from parent
back to child


In [4]:
"""[abstarct class]: This class is derived from abc import ABC(abstarct base class
) ,ABC is a meta class which defines behaviour of other class abstract method
 of an  abstract class must be defined in child class.
 It is use when common fetures are shared by all objects as they are.
 
 ex: From abc import ABC,abstractmethod"""

from abc import ABC,abstractmethod
class Defence(ABC):
    @abstractmethod
    def area(self):
        pass
    def gun(self):
        print("Gun is AK-47")
class Army(Defence):
    def area(self):
        print("area is land")
class Navy(Defence):
    def area(self):
        print("area is sea")
a=Army()
b=Navy()
a.area()
a.gun()
b.area()
b.gun()

area is land
Gun is AK-47
area is sea
Gun is AK-47


In [6]:
#METHOD RESOLUTION ORDER:
class A:
    def which(self):
        print("I am from A")
class B(A):
    def which(self):
        print("I am from B")
class C(A):
     def which(self):
        print("I am from C")
class D(C,B):
     def which(self):
        print("I am from D")
d=D()
d.which()
D.mro()  # type D and press . and tab and selct mro

I am from D


[__main__.D, __main__.C, __main__.B, __main__.A, object]

In [17]:
#DUNDER /SPECIAL/MAGIC METHOD
class Book:
    def __init__(self,title,author,pages):
        print("A book created")
        self.title=title
        self.author=author
        self.pages=pages
    def __str__(self):
        return f"A{self.title} book by {self.author}"
    def __len__(self):
        return self.pages
    def __del__(self):
        print("book destroyed")

In [ ]:
#DUNDER /SPECIAL/MAGIC METHOD
class Book:
    def __init__(self,title,author,pages):
        print("A book created")
        self.title=title
        self.author=author
        self.pages=pages
    def __str__(self):
        return f"{self.title} book by {self.author}"
    def __len__(self):
        return self.pages
    def __del__(self):
        print("book destroyed")
b=Book("raja ki rani","rajan",1000)        

In [13]:
print(b)

raja ki rani book by rajan
