<center><h1> NUMPY EXERCISE </h1></center>

## Create a 1D NumPy array named arr1 with elements [1, 2, 3, 4, 5].

In [6]:
import numpy as np
arr1=np.arange(1,6)
print(arr1)

[1 2 3 4 5]


## Create a 2D NumPy array named arr2 with elements [[6, 7, 8], [9, 10, 11]].

In [4]:
arr2=np.arange(6,12).reshape(2,3)
print(arr2)

[[ 6  7  8]
 [ 9 10 11]]


## Perform array indexing to extract the element 4 from arr1 and the element 10 from arr2.

In [10]:
print(arr1.item(3))
print(arr2.item(1,1))

4
10


## Use array slicing to create a new 1D array slice_arr from arr1 containing elements [2, 3, 4].

In [18]:
arr1[1:4]

array([2, 3, 4])

## Determine the shape of arr2.

In [11]:
arr2.shape

(2, 3)

## Reshape arr1 into a 3x2 array named reshaped_arr.

In [15]:
arr1=np.arange(1,7)
print(arr1.reshape(3,2))


[[1 2]
 [3 4]
 [5 6]]


## Iterate through the elements of arr2 and print each element.

In [23]:
arr2=np.arange(6,12).reshape(2,3)
for i in np.nditer(arr2):
    print(i)

6
7
8
9
10
11


## Use the np.concatenate function to concatenate arr1 and arr2 horizontally into a new array named concatenated_arr.

In [27]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)
np.concatenate((c,d),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## Use the np.array_split function to split concatenated_arr into three equal-sized arrays.

In [28]:
a=np.array([1,2,3,4,5,6])
new=np.array_split(a,3)
print(new)

[array([1, 2]), array([3, 4]), array([5, 6])]


## Use the np.where function to find the indices of elements in concatenated_arr that are greater than 5.

In [30]:
y=np.arange(1,20)
print(y)
print(np.where(y>10))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(array([10, 11, 12, 13, 14, 15, 16, 17, 18], dtype=int64),)


## Use the np.sort function to sort arr1 in ascending order.

In [32]:
a=np.array([5,1,3,6,4])
print(np.sort(a))
print(np.sort(a)[::-1])

[1 3 4 5 6]
[6 5 4 3 1]


__.__
<!-- import numpy as np

# 1. Create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2. Create a 2D array
arr2 = np.array([[6, 7, 8], [9, 10, 11]])

# 3. Array indexing
element_from_arr1 = arr1[3]  # Element: 4
element_from_arr2 = arr2[1, 1]  # Element: 10

# 4. Array slicing
slice_arr = arr1[1:4]  # Elements: [2, 3, 4]

# 5. Determine the shape
shape_of_arr2 = arr2.shape  # Shape: (2, 3)

# 6. Reshape arr1 (using size 5)
reshaped_arr = arr1.reshape(1, 5)  # Reshape to a 1x5 array

# 7. Iteration
for element in np.nditer(arr2):
    print(element)

# 8. Concatenate horizontally after reshaping arr1
reshaped_arr = np.repeat(reshaped_arr, arr2.shape[0], axis=0)  # Repeat rows to match arr2
concatenated_arr = np.concatenate((reshaped_arr, arr2), axis=1)

# 9. Array splitting
split_arrays = np.array_split(concatenated_arr, 3)

# 10. np.where
indices_gt_5 = np.where(concatenated_arr > 5)

# 11. np.sort
sorted_arr1 = np.sort(arr1)

# Display results
print("Element from arr1:", element_from_arr1)
print("Element from arr2:", element_from_arr2)
print("Sliced array:", slice_arr)
print("Shape of arr2:", shape_of_arr2)
print("Reshaped arr1:", reshaped_arr)
print("Concatenated array:", concatenated_arr)
print("Split arrays:", split_arrays)
print("Indices greater than 5:", indices_gt_5)
print("Sorted arr1:", sorted_arr1)
 -->